application: brid-gy
version: 2
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: 1d

builtins:
- remote_api: on
- appstats: on

libraries:
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /webmention
  script: webmention.application
  secure: always

- url: /(post|comment|like|repost)/.*
  script: handlers.application
  secure: always

- url: /facebook/.*
  script: facebook.application
  secure: always

- url: /googleplus/.*
  script: googleplus.application
  secure: always

- url: /instagram/.*
  script: instagram.application
  secure: always

- url: /twitter/.*
  script: twitter.application
  secure: always

- url: /log
  script: logs.application
  secure: always

- url: /_ah/queue/.*
  script: tasks.application
  login: admin
  secure: always

- url: /(delete/.*|about)?
  script: app.application
  secure: always

- url: .*
  script: app.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*
