application: brid-gy
version: 7
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: 1h

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  # min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 12

builtins:
- remote_api: on
- appstats: on

libraries:
- name: lxml
  version: latest
- name: ssl
  version: latest
- name: webob
  version: latest

inbound_services:
- warmup

handlers:

# static
- url: /(static/bootstrap.*\.css)
  static_files: local/lib/python2.7/site-packages/oauth_dropins/\1
  upload: local/lib/python2.7/site-packages/oauth_dropins/static/bootstrap.*\.css

- url: /static
  static_dir: static

- url: /static/style.css
  static_files: static/style.css
  upload: static/style.css

- url: /static/bridgy.js
  static_files: static/bridgy.js
  upload: static/bridgy.js

- url: /oauth_dropins/static
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/static

- url: /fonts
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/fonts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# dynamic
- url: /(post|comment|like|react|repost|rsvp)/.+
  script: handlers.application
  secure: always

- url: /blogger/(start|add|delete|notify|oauth2callback|oauth_handler)(/.*)?
  script: blogger.application
  secure: always

- url: /facebook/(start|oauth_handler|add|delete|publish/.+)(/.*)?
  script: facebook.application
  secure: always

- url: /flickr/(start|add|delete|publish)(/.*)?
  script: flickr.application
  secure: always

- url: /googleplus/(start|add|delete|oauth2callback)(/.*)?
  script: googleplus.application
  secure: always

- url: /instagram/(start|indieauth|callback|add|delete/.+)(/.*)?
  script: instagram.application
  secure: always

- url: /medium/(start|add|delete|notify|choose_blog)(/.*)?
  script: medium.application
  secure: always

- url: /tumblr/(start|add|delete|notify|choose_blog)(/.*)?
  script: tumblr.application
  secure: always

- url: /twitter/(start|add|delete|publish/.+)(/.*)?
  script: twitter.application
  secure: always

- url: /wordpress/(start|add|delete|notify|confirm)(/.*)?
  script: wordpress_rest.application
  secure: always

- url: /webmention/(blogger|medium|tumblr|wordpress)
  script: blog_webmention.application
  secure: always

- url: /log
  script: logs.application
  secure: always

- url: /publish/.+
  script: publish.application
  secure: always

- url: /_ah/queue/.+
  script: tasks.application
  login: admin
  secure: always

- url: /cron/.+
  script: cron.application
  login: admin
  secure: always

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always

# - url: /_info
#   script: oauth_dropins.webutil.instance_info.application
#   secure: always

- url: /admin/.*
  script: admin.application
  secure: always

- url: /(_ah/warmup|about|crawl-now|csp-report|delete/start|delete/finish|listen|logout|publish|poll-now|retry|users)?/?
  script: app.application
  secure: always

- url: /(blogger|facebook|fake|flickr|googleplus|instagram|medium|tumblr|twitter|wordpress)/.+
  script: app.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(\.?coverage|debian|docs?|examples?|l|pydocs?|python3|ref|samples?|TAGS|tests?)/.*
- ^local/lib/python2.7/site-packages/setuptools/script\ \(dev\)\.tmpl$
