application: brid-gy
version: 1
runtime: python
# threadsafe: false
api_version: 1
default_expiration: 1d

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /facebook/.*
  script: facebook.py
  login: required

- url: /wordpress/.*
  script: wordpress.py
  login: required

- url: /_ah/queue/.*
  script: tasks.py
  login: admin

- url: /
  script: app.py
  # not secure: always because app engine can't (yet) do ssl on custom domains
  # like brid.gy
  # secure: optional

- url: .*
  script: app.py
  login: required
