application: brid-gy
version: 2
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: 1d

builtins:
- remote_api: on

libraries:
- name: ssl
  version: latest

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /webmention
  script: webmention.application

- url: /facebook/(post|comment)/.*
  script: facebook.application
  # login not required for post/comment handlers

- url: /facebook/.*
  script: facebook.application
  login: required

- url: /googleplus/.*
  script: googleplus.application
  login: required

- url: /instagram/.*
  script: instagram.application
  login: required

- url: /twitter/.*
  script: twitter.application
  login: required

- url: /_ah/queue/.*
  script: tasks.application
  login: admin

- url: /
  script: app.application
  # not secure: always because i haven't bought an SNI slot for SSL on the
  # brid.gy custom domain.
  # secure: optional

- url: .*
  script: app.application
  login: required

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*
