application: brid-gy
version: 1
runtime: python
api_version: 1
default_expiration: 1d

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /facebook/.*
  script: facebook.py
  login: required

- url: /wordpress/.*
  script: wordpress.py
  login: required

- url: /_ah/queue/.*
  script: tasks.py
  login: admin

- url: /
  script: app.py
  secure: always

- url: .*
  script: app.py
  secure: always
  login: required
